server.port=${SERVER_PORT:8081}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/erikbank}
spring.datasource.username=${DB_USER:erikbank}
spring.datasource.password=${DB_PASSWORD:erikbank}
spring.datasource.driver-class-name=org.postgresql.Driver
